version: "3.8"
services:
  mysql_service:
    container_name: mysql_service
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: psw123
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 666
    ports:
      - "3306:3306"
    networks:
      mynet:
        ipv4_address: 6.6.0.5
  api_service:
    container_name: api_service
    build:
      context: .
      dockerfile: ./db_api/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mysql_service
    networks:
      mynet:
        ipv4_address: 6.6.0.6
networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 6.6.0.0/16